name: Run tagpr

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissios:
  contents: read
  pull-requests: write

jobs:
  tagpr:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: Songmu/tagpr@v1
        with:
          version: "v1.3.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
