name: Run tagpr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tagpr:
    runs-on: ubuntu-22.04
    permissions:
      # for create releases
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: Songmu/tagpr@v1
        with:
          version: "v1.3.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
